import type { Metadata, Viewport } from "next";

export const metadata: Metadata = {
  title: "PWA App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  themeColor: "#ffffff",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex font-nexa min-h-screen overflow-x-hidden overflow-y-scroll no-scrollbar">
          {children}
      </body>
    </html>
  );
}
